### PR TITLE
Benchmarking added

### PR DESCRIPTION
**Pull request by yazhai**
@zonca @agoetz @ThuongTNguyen 
This pull adds the benchmarking on the function x2b_v9x::eval(w1, w2) that obtains the potential energy of the dimer. 
It is able to compare the benchmarking result with that from Neural Network model + CUDNN library.

### CODE REVIEW

**Comment by zonca** [comment]
I think it would be useful if somebody else in the team tries to run this benchmark code following the instructions in the README and see if it is enough. @ohamto would you like to do this? If you get stuck, you can ask @yazhai to help and then add what was not clear to the README.

**Comment by ohamto** [comment]
@zonca Sure thing. I'll get back to you in a bit.

**Comment by agoetz** [comment]
@yazhai I have not tested but looks good.

@ohamto Thanks for testing.

@zonca @yazhai OpenMM supports OpenMP. It would be nice to have an OMP parallel tester to see how this scales in reality from 1 to N cores on a full node. We could read the entire test set (or a subset) and parallelize a loop over all atoms. This would be a fair comparison against a GPU.

**Comment by zonca** [comment]
I am worried that OpenMP would take a large effort, not sure it is worth it.

**Comment by agoetz** [comment]
It should be easy. The mbpol library is thread safe. All we need is a small change to the driver, starting from `test-mbpol.cpp`, e.g. call it `benchmark-mbpol.cpp`. Instead of using a single dimer coordinate we loop over all dimer coordinates in the xyz file and use an omp pragma to do this in parallel.

We can add options or preprocessor flags for the mbpol library to do the full potential or only the polynomial part, so we can time outside of the parallel loop.

**Comment by zonca** [comment]
Ok

**Comment by fpaesani** [comment]
@yazhai @zonca @agoetz My $0.02. In the broad picture, having a non-GPU version of MB-MD is going to be very useful since will attract users that may not have access to GPUs.

**Comment by ohamto** [comment]
@yazhai @zonca I think the stuff on the README was enough. Here's what I got after running the script.
```
$ ./run_benchmarking.x 
Number of run samples (no gradient)   : 98 
Total   run time                 [ms] : 7667 
Average run time per sample      [ms] : 78.234694 
Total run time of  42105 samples [ms] : 3294071.785714 
```

**Comment by yazhai** [comment]
Hello @zonca @agoetz ,
The library itself is openMP enabled.
But as @agoetz said, the tester needs some update before we can make it really parallel, as the current tester reads in only a single sample input file, proceeds the calculation, and outputs the result.

So there are some work to do to make it parallel:
1. Redesign the tester. Instead of reading in a single sample file each time, the redesigned tester needs to read in ALL samples at the same time, and launch the calculations in parallel.
2. It would be a bit confused to time the runtime if the program is running in parallel.
At the moment I'm using the easiest way: outstream the runtime of this part into a text file so that we can view the runtime of each sample, then make the average.
The method I can think of when it runs in parallel is outstreaming the runtime with thread ID, summing up the time from same ID, and taking the maximum from all the sums as the runtime of parallel. Is this fair?
3. @agoetz is interested in seeing the runtime of different functions and how the openmp affects them. So I will make the timer in all several parts simultaneously.

**Comment by yazhai** [comment]
@ohamto thanks for your help on the benchmarking! 
Perhaps we need to make another run later with openMP enabled. Would you please have a try as well?
All the best.

**Comment by yazhai** [comment]
@fpaesani Thanks for your reminder on it.
We will make it as well.

**Comment by ohamto** [comment]
@yazhai Sure thing.

**Comment by yazhai** [comment]
Hello @zonca @agoetz ,
I have finished redoing the benchmarking programs on legacy_4d.
A new timer class is created.
A new tester is created, which can read in ALL tester samples and run then in sequence.
The program is OPENMP valid.
A new script is created for helping bench on different OPENMP thread number.

The result is far better than expected.
The function `E_poly = poly_2b_v6x::eval()`, which calculates the potential energy, runs for 0.2 seconds on average for all 42K samples with 1 OPENMP thread, and 0.014 seconds with 24 OPENMP threads.

The total time to run `E_nogrd = pot(nw, crd)` is 0.8s for 1 thread and 0.05s for 24 threads.

Please check the code and send me your feedback.

@ohamto would you please run the program as well?
The steps to run is written in README.
Thanks a lot!

Have a nice weekends!
Best,
Yaoguang

**Comment by ohamto** [comment]
Hi @yazhai, 
The steps to run are still pretty clear to me. Here's what I got from following the README on my machine at Urey:
```Running program with OMP THREADS 1
Running program with OMP THREADS 2
Running program with OMP THREADS 4
Running program with OMP THREADS 8
Running program with OMP THREADS 16
Running program with OMP THREADS 24
 Statistics of function runtime in [ms] for one thread :
           |            E_poly           |           E_2poly           |           E_nogrd           |            E_grd            |
 OMP_THRDS |    MEAN       MIN       MAX |    MEAN       MIN       MAX |    MEAN       MIN       MAX |    MEAN       MIN       MAX |
     1     |   6e+05   5.9e+05   6.1e+05 | 7.4e+05   7.3e+05   7.5e+05 | 1.8e+06   1.8e+06   1.8e+06 | 2.5e+06   2.5e+06   2.5e+06 |
     2     | 3.1e+05   3.1e+05   3.2e+05 | 3.8e+05   3.8e+05   3.9e+05 | 9.1e+05     9e+05   9.4e+05 | 1.3e+06   1.3e+06   1.3e+06 |
     4     | 1.6e+05   1.5e+05   1.7e+05 | 1.9e+05   1.9e+05     2e+05 | 4.6e+05   4.5e+05   4.7e+05 | 6.5e+05   6.4e+05   6.6e+05 |
     8     | 8.3e+04   8.1e+04   9.1e+04 |   1e+05   9.8e+04   1.1e+05 | 2.4e+05   2.3e+05   2.6e+05 | 3.3e+05   3.2e+05   3.6e+05 |
    16     |   6e+04   5.4e+04   7.4e+04 | 7.2e+04   6.7e+04   9.8e+04 | 1.8e+05   1.7e+05     2e+05 | 2.4e+05   2.3e+05   2.6e+05 |
    24     | 5.7e+04   3.6e+04   1.3e+05 | 6.9e+04   4.4e+04   1.4e+05 | 1.6e+05   1.1e+05   2.5e+05 | 3.1e+05   1.6e+05   4.9e+05 |
```

**Comment by yazhai** [comment]
@ohamto cool, thanks for your help!

**Comment by ohamto** [comment]
@yazhai Here are the relevant parts of `$ lscpu` from the machine where I ran the benchmarking 
```
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             2
```

**Pull request merged**
